// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "embedded_assistant.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_assistant_embedded_v1alpha2_AssistRequest, google_assistant_embedded_v1alpha2_AssistRequest, 2)


PB_BIND(google_assistant_embedded_v1alpha2_AssistResponse, google_assistant_embedded_v1alpha2_AssistResponse, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_DebugInfo, google_assistant_embedded_v1alpha2_DebugInfo, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_AssistConfig, google_assistant_embedded_v1alpha2_AssistConfig, 2)


PB_BIND(google_assistant_embedded_v1alpha2_AudioInConfig, google_assistant_embedded_v1alpha2_AudioInConfig, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_AudioOutConfig, google_assistant_embedded_v1alpha2_AudioOutConfig, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_ScreenOutConfig, google_assistant_embedded_v1alpha2_ScreenOutConfig, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_DialogStateIn, google_assistant_embedded_v1alpha2_DialogStateIn, 2)


PB_BIND(google_assistant_embedded_v1alpha2_DeviceConfig, google_assistant_embedded_v1alpha2_DeviceConfig, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_AudioOut, google_assistant_embedded_v1alpha2_AudioOut, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_ScreenOut, google_assistant_embedded_v1alpha2_ScreenOut, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_DeviceAction, google_assistant_embedded_v1alpha2_DeviceAction, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_SpeechRecognitionResult, google_assistant_embedded_v1alpha2_SpeechRecognitionResult, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_DialogStateOut, google_assistant_embedded_v1alpha2_DialogStateOut, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_DebugConfig, google_assistant_embedded_v1alpha2_DebugConfig, AUTO)


PB_BIND(google_assistant_embedded_v1alpha2_DeviceLocation, google_assistant_embedded_v1alpha2_DeviceLocation, 2)









