// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_GOOGLE_API_GOOGLE_API_ANNOTATIONS_PB_H_INCLUDED
#define PB_GOOGLE_API_GOOGLE_API_ANNOTATIONS_PB_H_INCLUDED
#include <pb.h>
#include "http.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Extensions */
extern const pb_extension_type_t google_api_http; /* field type: google_api_HttpRule http; */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
