// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_GOOGLE_API_GOOGLE_API_HTTP_PB_H_INCLUDED
#define PB_GOOGLE_API_GOOGLE_API_HTTP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _google_api_CustomHttpPattern {
    pb_callback_t kind;
    pb_callback_t path;
} google_api_CustomHttpPattern;

typedef struct _google_api_Http {
    pb_callback_t rules;
    bool fully_decode_reserved_expansion;
} google_api_Http;

typedef struct _google_api_HttpRule {
    pb_callback_t selector;
    pb_size_t which_pattern;
    union {
        pb_callback_t get;
        pb_callback_t put;
        pb_callback_t post;
        pb_callback_t delete_;
        pb_callback_t patch;
        google_api_CustomHttpPattern custom;
    } pattern;
    pb_callback_t body;
    pb_callback_t additional_bindings;
    pb_callback_t response_body;
} google_api_HttpRule;


/* Initializer values for message structs */
#define google_api_Http_init_default             {{{NULL}, NULL}, 0}
#define google_api_HttpRule_init_default         {{{NULL}, NULL}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_api_CustomHttpPattern_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define google_api_Http_init_zero                {{{NULL}, NULL}, 0}
#define google_api_HttpRule_init_zero            {{{NULL}, NULL}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_api_CustomHttpPattern_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define google_api_CustomHttpPattern_kind_tag    1
#define google_api_CustomHttpPattern_path_tag    2
#define google_api_Http_rules_tag                1
#define google_api_Http_fully_decode_reserved_expansion_tag 2
#define google_api_HttpRule_get_tag              2
#define google_api_HttpRule_put_tag              3
#define google_api_HttpRule_post_tag             4
#define google_api_HttpRule_delete_tag           5
#define google_api_HttpRule_patch_tag            6
#define google_api_HttpRule_custom_tag           8
#define google_api_HttpRule_selector_tag         1
#define google_api_HttpRule_body_tag             7
#define google_api_HttpRule_response_body_tag    12
#define google_api_HttpRule_additional_bindings_tag 11

/* Struct field encoding specification for nanopb */
#define google_api_Http_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  rules,             1) \
X(a, STATIC,   SINGULAR, BOOL,     fully_decode_reserved_expansion,   2)
#define google_api_Http_CALLBACK pb_default_field_callback
#define google_api_Http_DEFAULT NULL
#define google_api_Http_rules_MSGTYPE google_api_HttpRule

#define google_api_HttpRule_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   selector,          1) \
X(a, CALLBACK, ONEOF,    STRING,   (pattern,get,pattern.get),   2) \
X(a, CALLBACK, ONEOF,    STRING,   (pattern,put,pattern.put),   3) \
X(a, CALLBACK, ONEOF,    STRING,   (pattern,post,pattern.post),   4) \
X(a, CALLBACK, ONEOF,    STRING,   (pattern,delete,pattern.delete),   5) \
X(a, CALLBACK, ONEOF,    STRING,   (pattern,patch,pattern.patch),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pattern,custom,pattern.custom),   8) \
X(a, CALLBACK, SINGULAR, STRING,   body,              7) \
X(a, CALLBACK, REPEATED, MESSAGE,  additional_bindings,  11) \
X(a, CALLBACK, SINGULAR, STRING,   response_body,    12)
#define google_api_HttpRule_CALLBACK pb_default_field_callback
#define google_api_HttpRule_DEFAULT NULL
#define google_api_HttpRule_pattern_custom_MSGTYPE google_api_CustomHttpPattern
#define google_api_HttpRule_additional_bindings_MSGTYPE google_api_HttpRule

#define google_api_CustomHttpPattern_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   kind,              1) \
X(a, CALLBACK, SINGULAR, STRING,   path,              2)
#define google_api_CustomHttpPattern_CALLBACK pb_default_field_callback
#define google_api_CustomHttpPattern_DEFAULT NULL

extern const pb_msgdesc_t google_api_Http_msg;
extern const pb_msgdesc_t google_api_HttpRule_msg;
extern const pb_msgdesc_t google_api_CustomHttpPattern_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_api_Http_fields &google_api_Http_msg
#define google_api_HttpRule_fields &google_api_HttpRule_msg
#define google_api_CustomHttpPattern_fields &google_api_CustomHttpPattern_msg

/* Maximum encoded size of messages (where known) */
/* google_api_Http_size depends on runtime parameters */
/* google_api_HttpRule_size depends on runtime parameters */
/* google_api_CustomHttpPattern_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
