// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_GOOGLE_TYPE_GOOGLE_TYPE_LATLNG_PB_H_INCLUDED
#define PB_GOOGLE_TYPE_GOOGLE_TYPE_LATLNG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _google_type_LatLng {
    double latitude;
    double longitude;
} google_type_LatLng;


/* Initializer values for message structs */
#define google_type_LatLng_init_default          {0, 0}
#define google_type_LatLng_init_zero             {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define google_type_LatLng_latitude_tag          1
#define google_type_LatLng_longitude_tag         2

/* Struct field encoding specification for nanopb */
#define google_type_LatLng_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          1) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         2)
#define google_type_LatLng_CALLBACK NULL
#define google_type_LatLng_DEFAULT NULL

extern const pb_msgdesc_t google_type_LatLng_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_type_LatLng_fields &google_type_LatLng_msg

/* Maximum encoded size of messages (where known) */
#define google_type_LatLng_size                  18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
